version: '3'

services:
  pgadmin:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - /opt/ops/pgadmin/data:/data
    ports:
      - 5050:5050
    env_file:
      - pgadmin.env
